#ifndef BORDARECHEADA_GLOBAL_H
#define BORDARECHEADA_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BORDARECHEADA_LIBRARY)
#  define BORDARECHEADASHARED_EXPORT Q_DECL_EXPORT
#else
#  define BORDARECHEADASHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // BORDARECHEADA_GLOBAL_H
